return {
    "Alexis Ffrench – Bluebird",
    "Bach – Prelude in C Major",
    "Bach – Toccata and Fugue in D Minor",
    "Beethoven – Für Elise",
    "Beethoven – Moonlight Sonata (3rd movement)",
    "Beethoven – Pathetique Sonata",
    "Chopin – Fantaisie-Impromptu",
    "Chopin – Nocturne Op.9 No.2",
    "Debussy – Clair de Lune",
    "Grieg – In the Hall of the Mountain King",
    "Handel – Sarabande",
    "Joep Beving – Ab Ovo",
    "Liszt – Consolation No. 3",
    "Liszt – Hungarian Rhapsody No. 2",
    "Ludovico Einaudi – Experience",
    "Mendelssohn – Wedding March",
    "Mozart – Eine kleine Nachtmusik",
    "Mozart – Turkish March",
    "Nils Frahm – Ambre",
    "Pachelbel – Canon in D",
    "Philip Glass – Opening",
    "Richter – On the Nature of Daylight",
    "Ryuichi Sakamoto – Aqua",
    "Saint-Saëns – The Swan",
    "Satie - Gymnopédie No.1",
    "Satie – Gnossienne No.1",
    "Schubert – Ave Maria",
    "Tchaikovsky – Swan Lake Theme",
    "Vivaldi – Spring (Four Seasons)",
    "Yiruma – Indigo"
}
