return {
    "Celeste – Resurrections",
    "Chrono Trigger – Corridors of Time",
    "Cuphead – Floral Fury",
    "Deltarune – Field of Hopes and Dreams",
    "FNAF - Die In A Fire",
    "FNAF - Five Nights At Freddy's Song",
    "FNAF - I Got No Time",
    "Final Fantasy – To Zanarkand",
    "Genshin Impact – Rex Incognito",
    "Halo – Main Theme",
    "Hollow Knight – City of Tears",
    "Journey – Apotheosis",
    "Kingdom Hearts – Dearly Beloved",
    "League of Legends – Legends Never Die",
    "Minecraft – Sweden",
    "NieR Automata – Weight of the World",
    "Omori – My Time",
    "Persona 3 – Burn My Dread",
    "Persona 5 – Beneath the Mask",
    "Pokemon - Littleroot Town",
    "Portal – Still Alive",
    "Sonic – Green Hill Zone",
    "Splatoon – Calamari Inkantation",
    "Stardew Valley – Spring (It's a Big World Outside)",
    "Super Mario Galaxy – Gusty Garden",
    "The Elder Scrolls V Skyrim – Dragonborn",
    "The Living Tombstone - It's Been So Long",
    "Undertale - Fallen Down",
    "Undertale – His Theme",
    "Undertale – Hopes and Dreams",
    "Undertale – Megalovania",
    "Xenoblade Chronicles – You Will Know Our Names",
    "Zelda – Song of Storms"
}
