return {
    "Adele – Easy On Me",
    "BTS – Spring Day (Piano ver)",
    "Benson Boone – Beautiful Things",
    "Billie Eilish – Birds of a Feather",
    "Billie Eilish – Lovely",
    "BoyWithUke - Toxic",
    "Chappell Roan – Good Luck, Babe!",
    "Charlie Puth – See You Again",
    "Coldplay – Viva La Vida",
    "Ed Sheeran – Perfect",
    "Gracie Abrams – Risk",
    "Harry Styles – Sign of the Times",
    "Hozier – Too Sweet",
    "JVKE – golden hour",
    "Jamie Duffy - Solas",
    "Joji – Glimpse of Us",
    "Lady Gaga – Shallow",
    "Lana Del Rey – Young and Beautiful",
    "Lewis Capaldi – Someone You Loved",
    "Mitski – Washing Machine Heart",
    "Noah Kahan – Stick Season",
    "Olivia Rodrigo – drivers license",
    "Olivia Rodrigo – vampire",
    "OneRepublic – Counting Stars",
    "Sabrina Carpenter – Espresso",
    "Sam Smith – I'm Not the Only One",
    "Sia – Chandelier",
    "Tate McRae – greedy",
    "Taylor Swift – All Too Well (10 min ver)",
    "Taylor Swift – Fortnight",
    "The Kid LAROI & Justin Bieber – Stay",
    "The Living Tombstone - My Ordinary Life",
    "Yung Kai - Blue"
}
