return {
    "All Star – Smash Mouth",
    "Among Us Drip Theme",
    "Coffin Dance – Astronomia",
    "Crab Rave",
    "Darude – Sandstorm",
    "Dr. Dre - Still D.R.E",
    "Fireflies – Owl City",
    "Fur Elise x Still D.R.E",
    "Internet Meme – Oh No Sound Effect",
    "Linga Guli Guli",
    "Malice Mizer - Le Ciel",
    "Moonlight Sonata x Still D.R.E",
    "Nyan Cat Theme",
    "Rick Astley – Never Gonna Give You Up",
    "Running in the 90s",
    "Rush E",
    "Shrek Theme – Hallelujah",
    "Spooky Scary Skeletons",
    "Steven Universe Theme Lo-fi",
    "TheFatRat – Monody",
    "TheFatRat – Unity",
    "TheFatRat – Xenogenesis",
    "Thomas the Tank Engine",
    "Tokyo Drift"
}
