return {
    "Adele – Easy On Me",
    "BTS – Spring Day (Piano ver)",
    "Billie Eilish – Lovely",
    "Charlie Puth – See You Again",
    "Coldplay – Viva La Vida",
    "Ed Sheeran – Perfect",
    "Harry Styles – Sign of the Times",
    "Joji – Glimpse of Us",
    "Lady Gaga – Shallow",
    "Lana Del Rey – Young and Beautiful",
    "Lewis Capaldi – Someone You Loved",
    "Mitski – Washing Machine Heart",
    "Olivia Rodrigo – drivers license",
    "Olivia Rodrigo – vampire",
    "OneRepublic – Counting Stars",
    "Sam Smith – I'm Not the Only One",
    "Sia – Chandelier",
    "Taylor Swift – All Too Well (10 min ver)",
    "The Kid LAROI & Justin Bieber – Stay",
    "Yung Kai - Blue"
}
