name: Update Lua Return Files

on:
  push:
    paths:
      - 'Main/Presets/**'
  pull_request:
    paths:
      - 'Main/Presets/**'

permissions:
  contents: write

jobs:
  update-return-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0 # Ensures full history is fetched, needed for pull operations

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Update return files
      run: python .github/scripts/update_return_files.py

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code Main/returntables/ || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Fetch latest changes from remote
      run: |
        git fetch origin main # Fetch latest changes from the remote repository

    - name: Merge remote changes with rebase
      run: |
        git pull --rebase origin main # Rebase local changes on top of the remote changes to avoid merge commits

    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Main/returntables/
        git commit -m "Auto-update return files based on preset changes"
        git push origin main # Push the updates to the remote repository
